### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andresattler** [andresattler/game_jam#5]
- [x]  spawn system obstacles
- [x]  despawn system
- [x]  world bounds
- [x]  collision 
- [x]  life / game end (5 hits) 
- [x]  score (distance)
- [x]  shooting 
- [x]  different obstacles
- [ ]  obstacles moving towards player
- [ ] (texture) + optics
- [x] jumping
- [ ] Pause/menu
- [ ] Powerups
- [ ] Health container?

**Comment by andresattler** [comment]
I will start with the health component

**Comment by Haniyya** [comment]
Also:
* [ ] TTL Component and system for things that have a time to live

**Comment by Haniyya** [comment]
As promised Ill do world bounds.

**Comment by Haniyya** [comment]
#6 theres level bounds

**Comment by Haniyya** [comment]
Ill add a score next

**Comment by Haniyya** [comment]
#7 Here is score. This is so fun. I love specs :heart:

**Comment by andresattler** [comment]
health added in  #8

your right its fun after understanding the basics :+1:

**Comment by Haniyya** [comment]
Ill take collision next I think. Will probably be bigger.

**Comment by Haniyya** [comment]
Collision in #11

**Comment by andresattler** [comment]
I would start working on the spawn system wont be final but at least a first version

**Comment by andresattler** [comment]
basic obstacle spawn system #12
(will need way more finetuning later)

**Comment by Haniyya** [comment]
Despawn in #13

**Comment by Haniyya** [comment]
Ill try my hand on shooting next

**Comment by Haniyya** [comment]
Shooting in #15

**Comment by Haniyya** [comment]
Ill try jumping next

**Comment by andresattler** [comment]
spawn system mk2 in #16

**Comment by andresattler** [comment]
I will add some different obstacles with different appearance and different amount of health
(maybe some that can not be shot at) also in #16

**Comment by Haniyya** [comment]
Jumping in #17

**Comment by Haniyya** [comment]
Gonna do pause/menu before deadline!
